/**
 * Generated by the Shiro plugin. This interceptor class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityInterceptor {

    //customize me
    int order = HIGHEST_PRECEDENCE + 200

    ShiroSecurityInterceptor(){
        match(controller: /.*/)
        .excludes(controller: 'auth')
    }
    boolean after() { 
          true
    }
    boolean before() {
        return accessControl()
    }
    void afterView() {
    }
}
