/**
 * Generated by the Shiro plugin. This interceptor class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityInterceptor {

    //customize me
    int order = HIGHEST_PRECEDENCE + 200

    ShiroSecurityInterceptor(){
        matchAll().excludes(controller: 'auth')
    }
    boolean after() { 
        true
    }
    boolean before() {
        if (accessControl()) {
            return true
        } else {
            return false
        }
    }
    void afterView() {
        
    }
}
