@package.line@/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class @filters.name@ {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName || controllerName == 'assets') return true

                // Access control by convention.
                accessControl()
            }
        }
    }
}
