import org.apache.shiro.SecurityUtils
import org.apache.shiro.authz.AuthorizationException
import org.apache.shiro.authz.UnauthenticatedException
import org.apache.shiro.web.util.WebUtils

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                return true
            }
//            afterView = { e ->
//                while (e && !(e instanceof AuthorizationException)) {
//                    e = e.cause
//                }
//
//                if (e instanceof AuthorizationException) {
//                    if (e instanceof UnauthenticatedException) {
//                        // User is not authenticated, so redirect to the login page.
//                        flash.message = "You need to be logged in to continue."
//                        redirect(
//                                controller: 'auth',
//                                action: 'login',
//                                params: [targetUri: request.forwardURI - request.contextPath])
//                    } else {
//                        redirect(controller: 'auth', action: 'unauthorized')
//                    }
//                }
//
//            }
        }
    }
}
